sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product sqr-033
env:
  global:
    -
      # LTD_AWS_ID
      secure: vqDHeEA7YDTuypqcJpOPwpBR473ILzqnO6+TxE6Hbsrtab/4SxibyisRAx73FUgumv+iRepwRBjaNeKxNT/dpwi9ldjauZzLnNm9DSUCbpEkWQYuSJQLcHz/fui/M69xRkp+sNxoiUJ5rHaFKwSFcBGH1Xq2UJosfy13Ve1TUf+ZJciq/3b/gNJWQQJXYWkqPT6C0Jv8739OPrAW03ey3sb+xQDIweEk8WYDp0+fKAkuW1qQlgMjVcUMsvfTGld0nJTSM2tx6v6yrckbzNvaPVmKqbb798S4JxgrrsP/nWdvPRca5oD8CpodZ8sfcjbc00/kXl6rXqW4FGE8zgqyA9eJaD2ZfXGG9vqlV1u18CTCgFgN8+7pgOEzynXB3RRKNjMxNXG3ShCog9f50FVKgn2AnuKuCVtv2R5D+GPW0ZKdMjw/H9tpxH/XQo81DvYGA1g4b6a2BiEg5h/f8JCDlTYomD9p7v/m6jGV2GWkLM3p/cFqqnTWJNDTVHcTRxV2rR+8+Vwbw8kRHW0FiH+mPQLKOFEoZ/qtSS1XfZK7hG7JFzL5ascEWkdGSK7bbhPbv0cGJc8zB4cS5da7LUqwAquRcQi0hzAjUj0D5KOfP8xcL9nmue3I5kGHyQSOmXNG76kWsHC4FzKfWtGMydkHyVND8NqZOFoWHT9zyO94Enk=
    -
      # LTD_AWS_SECRET
      secure: V0zR89D3BSbTdR8QvW4ggRnJMVkJBFt+nhOzUSTOB5B/XpAWcO1HqB5IYLCgskNDbXnoqh6runGyOoR9n54xoF+SxRM+WnRC2c/D9EqLjVWcatjCB2xsPNglkqWNdGYNU1UjOeQpEYiKMtYo60yRnh1SCi621ukfDKTm6Ogd5VY8elfoT0PhIezvTNu8i29CWL8sZXOedKC45lI7iIcfH53MEpIK1x8sa99QBJvZv1f5CHBJB8DOB4ThnNCve4+fvoKE7sTv4vcITqdxmAh0ruGvi5h30VQo8BV3wC8DWwA1Zz0hXZ/z7PAJJOEdEaBdnrE1iM4uES95r9rW3mNRd70Z4VtODz2uSKmqLj2LB4X4VPn6/axjGR0YOukIx+ZpMPDtgfEr3uX1uv8vJXFZEiRL2f78qbAGu7/arup0ygKtsKRKJn8kHY4v7BTm+eUcFjFpKgBECIJifF2rWZgVBpQbhvBP3JbFNKooAON/sRSC/XYwtgCCv+h7sUEkxqQY9fnnZ9T+I767ra3npOobvtYKaIMEyU1XTAzyBxtURtTV41a5nlT40swgVkfqMXwNXDMAHt283aLeotue5XtYbDPoDi5Z+RajwapsZePmxs05MNjdljKYQy0yckyZO+dS/vX2doZOfhgQDox4LJtIpj/VjH9NyELjmVo5g03TlNw=
    -
      # LTD_USERNAME
      secure: DL4ScmxY+e/M+vXw8XlcsFXoTLJahyuGVKxYA5aSGw6SWSQoGgutv2THOWDmInirO6dRr0JRCcydduvLJOBoWvaU2ovviak0a7t3ZszSfpO2BZnb9NtMR7dTpdJKDml6Nz1lVPIxYPMWUbn1Kv45bT4syBP7XScX9T7xQzEgtEgzCP4+pRFib2dIbZFjB1IGeUc61RgErxYY5p3Zjmk0Kyysj1ym40IjJopMse/4JG3JmZfe0c3PKIZlOQIXj/DG6Lt3GJGJqR6BPwPtGeP8BHruK/8dVUdQx4WYW4GbFozeuI0/dfZe1r42Ns2WfkKJPAsBeae5SKnVoRI/gdFw6q3GITyyMQC5zTx2z/kTQQjqrWfzmVhJpnIn0dwBw7dDhZj4kPQtW2+bCxXOWjGnHhtFaPyoEMmOjxBrHyKtMAfpBjwwZCO7vhwwCF/Uym+Pg5ziMueA/dpo4An6WUJoMGGoyC4NRGLzd11fuge0qJHxNv9AxcZoxW0vF4KXUdHzt/F0YlwNdhYWIro7ExoyWMYcO4ms7/RhaRWyhZjj+3Hdsh0ybMHpHdcbClS+/vsxud/7TTNogiHKCEtFiGxwCZAKMDuvycc9biZ72PT99/QnE+UphdWc3yeVtBT2tQP/lCmHJNuDHRdndYih+VKL4mdeOhDFyqe4ESQ8Q6QcD3Q=
    -
      # LTD_PASSWORD
      secure: Ln7x1ZtCk31bdjQrmEBFygYI4jit8bgC1zpxnIzBCYrDlBY+X9gtQXZmtGBgq/4XdjEETWVYPcsF0WjNKEBznrne+0Q9mBpUk/sbR/A2ldeXT57zwvo46JE8ABvoxi2c6esO5FfwCUHFn2mG4ifTPHMzxEQuI6uW35KiKyQXKu5VE31Na1wTdVdBmmQbuepOWl5zyADkOD8t0/PodI5RFYOQq+HfMqXlp3UQiWYfreolYi+pPEU5HVsCGFnDEh7nDrbjg2hrcmcvg/6gxaYj8JrYeYWFLTPvA+U4G7jvcQGXzoz5z/jtl2W7g+rCkovTfTBzhrkks1XiZC6l1/xD528V78TfS/rnc6+hYtevRJ3yJhwHQJH6PK+2IgOM9KIeJoSMCSAcRvzmB+RLDMTNLXYC5/4Peu4RRyzevEhhkUwoc48fgmKx8/VzZkyf7sSXj5zBUVYTXDMwm5L6mgU+F1LHXnHi7eX8kQHwjINGaj6PhEslucLhoI9S0LxIHb6C6ndFPzjjqUo+Mz9QnNV0ShFG3vu3dPK4JwifX8eIYs12V9yujFmydxKIpm2JltyVYQp2cLQjG9F3V2NLRe8GzTGlILHVdpOAVP+FtPmYDe5oNJOD6pueULCnEdiYVWhJnXTfl93GiAFlq2ZLNU2o9LYcCII0JdGwgKOoK7W7U8o=
